plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - CONTRIBUTORS.md
  - LICENSE
  - docs/docs.md
  - docs/arc42.md
  - docs/deps.md
  - docs/schema.md
theme: slate
